version: 2

jobs:
  "test":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-v2-launcher-electron:0.0.6
    steps:
      - checkout
      - restore_cache:
          key: node-cache-v2{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-v2{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run test
          no_output_timeout: 1m

  "build":
      docker: *DOCKERIMAGE
      steps:
        - checkout
        - attach_workspace:
            at: .
        - restore_cache:
            key: node-cache-v2{{ checksum "package.json" }}
        - run: npm run build
        - save_cache:
            key: node-cache-v2{{ checksum "package.json" }}
            paths:
              - ./node_modules
        - persist_to_workspace:
            root: .
            paths:
              - build

  "stage":
      docker: *DOCKERIMAGE
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run: npm install common-display-module
        - run:
            name: Stage
            command: node_modules/common-display-module/stage.sh
            environment:
              MODULENAME: watchdog
        - persist_to_workspace:
            root: .
            paths:
              - version

  "deploy-beta":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-v2{{ checksum "package.json" }}
      - run: npm install common-display-module
      - run:
          name: Deploy to beta
          command: node_modules/common-display-module/deploy.sh
          environment:
            MODULENAME: watchdog

  "deploy-stable":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-v2{{ checksum "package.json" }}
      - run: npm install common-display-module
      - run:
          name: Deploy to stable
          command: node_modules/common-display-module/deploy.sh
          environment:
            MODULENAME: watchdog
            BRANCH: STABLE

workflows:
  version: 2
  workflow1:
    jobs:
      - "test"
      - "build":
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - build/stable
                - /^stage\/.*/
                - /^staging\/.*/
      - "stage":
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - build/stable
                - /^stage\/.*/
                - /^staging\/.*/

      - "deploy-stable":
          requires:
            - stage
          filters:
            branches:
              only:
                - build/stable

      - "deploy-beta":
          requires:
            - stage
          filters:
            branches:
              only:
                - master
